"""add last_online

Revision ID: 052d615ba0c2
Revises: d3e47748e006
Create Date: 2022-05-23 12:28:26.330661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052d615ba0c2'
down_revision = 'd3e47748e006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_online', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_online')
    # ### end Alembic commands ###
