"""add program

Revision ID: 1347f99cb5e1
Revises: 86777345f22d
Create Date: 2022-05-31 22:03:33.081854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1347f99cb5e1'
down_revision = '86777345f22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('program', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'program')
    # ### end Alembic commands ###
