"""make unique by user_id & friend_id

Revision ID: 77a18a2095f2
Revises: e46bcb6c2ee3
Create Date: 2022-05-16 10:21:01.125699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a18a2095f2'
down_revision = 'e46bcb6c2ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friends', ['user_id', 'friend_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='unique')
    # ### end Alembic commands ###
