"""Add Chats, UsersChats, Messages

Revision ID: 840efe6f6a5e
Revises: 052d615ba0c2
Create Date: 2022-05-26 04:46:01.160392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840efe6f6a5e'
down_revision = '052d615ba0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created'), 'messages', ['created'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('users_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id')
    )
    op.create_index(op.f('ix_users_chats_chat_id'), 'users_chats', ['chat_id'], unique=False)
    op.create_index(op.f('ix_users_chats_user_id'), 'users_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_chats_user_id'), table_name='users_chats')
    op.drop_index(op.f('ix_users_chats_chat_id'), table_name='users_chats')
    op.drop_table('users_chats')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
