"""add year

Revision ID: 86777345f22d
Revises: f0c543806e28
Create Date: 2022-05-31 22:03:13.478525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86777345f22d'
down_revision = 'f0c543806e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year')
    # ### end Alembic commands ###
