"""change birthday type

Revision ID: b0ab0b83a91d
Revises: 100141c7ea11
Create Date: 2022-06-01 04:45:39.124674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0ab0b83a91d'
down_revision = '100141c7ea11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=mysql.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
