"""add unique index

Revision ID: bb82083820dc
Revises: 5522d6eafb99
Create Date: 2022-05-23 02:25:11.630499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb82083820dc'
down_revision = '5522d6eafb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post_likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='unique')
    # ### end Alembic commands ###
