"""rename user_id to author_id

Revision ID: d3e47748e006
Revises: bb82083820dc
Create Date: 2022-05-23 08:42:12.803272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3e47748e006'
down_revision = 'bb82083820dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_index('ix_posts_user_id', table_name='posts')
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.create_index('ix_posts_user_id', 'posts', ['user_id'], unique=False)
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
