"""add city

Revision ID: f0c543806e28
Revises: 627605dfa887
Create Date: 2022-05-31 22:01:51.398609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0c543806e28'
down_revision = '627605dfa887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('group', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
